; Script generated by Gemini CLI

#define MyAppName "Clinic Manager"
#define MyAppVersion "1.0"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "updater.exe"
#define MyAppExeName1 "app.exe"
#define MyLauncherIcon "lancher-removebg-preview.ico"

[Setup]
AppId={{33DCA6E6-5869-4DB5-9478-3B6F03CCB7A7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputBaseFilename=mysetup
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Files]
Source: "updater.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "lancher-removebg-preview.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "launcher.ps1"; DestDir: "{app}"; Flags: ignoreversion

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "powershell.exe"; Parameters: "-WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\launcher.ps1"""; IconFilename: "{app}\{#MyLauncherIcon}"; Tasks: desktopicon

[Run]
Filename: "powershell.exe"; Parameters: "-WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\launcher.ps1"""; Description: "Launching {#MyAppName}..."; Flags: nowait postinstall skipifsilent
